ConduceInc/conduce-python-api

- config.py
Also fixed formatting of API key printing
> Don't mistake banksy-dev for shorthand for dev-app

- session.py
API calls for validate-session and login stopped working.  Updated to new API version.
> Updated to new APIs

- conduce.py
- util.py
Removed jsbeautifier references missed the first time around
> Removed jsbeautifier

- api.py
- conduce.py
- config.py
- session.py
- setup.cfg
- util.py
This defines the style and applies pep8 to the whole project.
> Add pep8 config and apply style

- conduce.py
Headers contain important information
> Print response headers

- api.py
- conduce.py
Create, list, add users and list users
> teams and groups

- api.py
- conduce.py
Add bindings for setting permissions on conduce resources
> Permissions API

- acl.py
Move acl functions out of dhl-pilot.
This requires documentation on the format of the permissions and teams object structures.
> Added acl library

- acl.py
- api.py
Just change 'thing' to 'resource'
> thing to resource

- acl.py
- api.py
Added APIs to find existing resources.  Required for "soft" building orchestrations.
> find resources

- api.py
- conduce.py
Added `/datasets/clear/{id}` API method and did some CLI arg parse cleanup.
> Add clear dataset command

- api.py
- conduce.py
- setup.py
- util.py
Update create-dataset and added ingest-data subcommand.  Also updated
ingest to populate endtime with timestamp if no endtime was provided in
the data.
> Added ingest data command

- api.py
> Removed debug print

- api.py
- conduce.py
This PR follows the patch PR and does some general cleanup.
> v2 api cleanup

- conduce.py
Response content is returned from create resource API.  This function wasn't updated so it was crashing after creation of the dataset.
Only effects CLI.
> Handle output from v2 resource api

- api.py
- util.py
This PR adds the `ingest_samples` API.  This API accepts sample lists as defined in sphinx docs.
To build the sphinx docs run `make html` in the `docs` directory of the repo.  You should also pip install requirements.txt.
> SKW-1981: Add ingest_samples API

- api.py
SKW-2024 original fix missed an instance of 'id' needing to be converted to string
> convert int to string

- conduce.py
Added utility to dump all entries from a dataset.
This seems to work fine with default values, but specifying other values for the ranges does not seem to work.  Seems like the API endpoint is not functioning as expected.
> Added dump data utility

- api.py
- setup.py
Just added a missing underscore.
Where's the automated testing?
> Added missing underscore

- README.md
- api.py
- doc/source/api-key-creation.rst
- doc/source/conduce-entities.rst
- doc/source/data-ingest.rst
- doc/source/entity-sample-definitions.rst
- doc/source/index.rst
also cleaned up table of contents in hopes of reordering PDF.
Incorporated most of the input from:
https://drive.google.com/file/d/0B20509pH_oTkQklINV9TVGZFMS1ObTA1NENzam1Wc1dOTjU4/view
> SKW-2067: Incorporated review from Troughton

- doc/source/conduce-entities.rst
- doc/source/data-ingest.rst
changes suggested by kvl in google doc.
> made revisions in pink

- requirements.txt
- util.py
Reverts ConduceInc/conduce-python-api#78
> Revert "SKW-2267: Add json to csv util"

- asset.py
- conduce.py
Added a command for uploading images.  This is a convenience for creating asset resources for image mime types.
> Added image upload command

- setup.py
This should be merged after the new command PRs.
> Increment minor version

- conduce.py
- setup.py
Return value was modified but the usage was not
> Bugfix: get entity is json

- samples/create_world_cities.py
Found this story:
https://sb-mct.atlassian.net/browse/SKW-2048
That said I was supposed to add tags to the resources, so I did.
> Add tags to resources created here

- session.py
Removed printing the password when logging in.
> SKW-2853 Remove print of password

- samples/create_world_cities.py
- samples/world-cities-heat.json
- setup.py
Added a heatmap lens for world cities data.
I tested this on stg-app where world cities had never been loaded.
> Added heatmap lens

- conduce.py
- setup.py
```python conduce.py dataset metadata --regex=.*cmx --host=dhl-stg-app.conduce.com --user=dhl-dev@conduce.com | jq .[0].t_max```
This command will help write shell scripts for generating dataset sensu alerts.
> Added dataset metadata cli

- conduce.py
Creates a new resource with a new name from an existing resource.
Also fixed more copy paste errors in parser names.
> Added copy resource command

- conduce.py
Just fixed some copy/paste mistakes.
> Replaced dataset with resource in help text

- doc/source/data-ingest.rst
- doc/source/index.rst
Reworded a few things for clarity.  Changed "constant entities" to "static entities" for consistency throughout the documentation.  Expanded "Intro" to "Introduction" for formality.
> Minor doc updates

- api.py
- setup.py
The internal API now returns a response object instead of True
The external API now waits for jobs to complete.
> SKW-3620: Wait for datasets to clear

- asset.py
and update print to python3 syntax
Function has fallback if name is not provided by crashes if name does not exist.
> Conditionally remove name kwarg

- samples/create_world_cities.py
World Cities data should  be an infinite time set.
> Add infinite flag to create_world_cities

- README.md
- requirements-dev.txt
- test/test_api.py
Adds unit tests for `create_resource` and adds documentation to README for running them.
> SKW-4064: Setup unit tests

- conduce/api.py
I vaguely remember there was a bug with name.  Anyway, it works now!
> Uncomment name filtering code from search query

- conduce/cli.py
Forgot this one the other day.
This allows a user to update a resource from a file.  It enables a nice workflow where you work on a file in your local editor and then push it to the server.  I used it extensively in my most recent lens development effort.
> Enable user to edit resource content from file

- .gitignore
- Jenkinsfile
- README.md
- conduce/util.py
- doc/Makefile
- requirements-dev.txt
- setup.py
- test/test_util.py
- tools/jenkins/common.groovy
- tools/jenkins/pipeline_master.groovy
- tools/jenkins/pipeline_pr.groovy
Based on the everything Jenkinsfile
See: https://jenk.mct.io/job/conduce-python-api/
> Add Jenkins integration

- .gitignore
- tools/jenkins/common.groovy
Just noticed a slackSend that got missed.  Also added a couple more
directories to .gitignore that should not be updated.
> change channel for slacksend, update gitignore

- README.md
- conduce/api.py
- conduce/cli.py
- conduce/config.py
- conduce/session.py
- conduce/util.py
- requirements-dev.txt
- test/test_api.py
- test/test_util.py
Help support style checks in pre-commit hooks
> add pycodestyle

- conduce/api.py
- test/test_api.py
> Add set_default_backend api method

- conduce/api.py
- conduce/cli.py
- test/test_api.py
- test/test_cli.py
- test/test_util.py
Functionally tested by adding backends and processing transactions in several environments.
> SKW-4168: backends cli

- conduce/cli.py
- test/test_cli.py
Found this to be quite helpful: 
```
[18:29:14] conduce-mbp-kvl:conduce-python-api kvl$ ./conduce-api dataset backend-status 8b86dbe3-9398-4cbd-8834-b5798916c9a1  --host=app.conduce.com 
8b86dbe3-9398-4cbd-8834-b5798916c9a1:
HistogramStore::e7f6add3-beb7-11e9-829b-3215067658a1: processed 3464 of 3464 transactions
CappedTileStore::a90ec4bc-beb7-11e9-b4a0-a2fac95a8ece: processed 2926 of 3464 transactions
```
> backend status cli

- conduce/cli.py
Was having to guess which output belonged to which backend when --all-backends was specified.
> Print ID of backend with location header

- conduce/api.py
- conduce/util.py
- test/test_api.py
- test/test_util.py
Enable users to set the minimum zoom level by specifying the dimension of the minimum zoom level.
> zoom level by length

- Jenkinsfile
- tools/jenkins/common.groovy
- tools/jenkins/pipeline_pr.groovy
Update Jenkinsfile to work with new Jenkins server.
Checkout the status of this build on the new server here:
https://jenkins.mct.io/job/conduce-python-api/view/change-requests/job/PR-182/
> SKW-4251: Migrate to k8s Jenkins

- Makefile
Added this when I was working on the Jenkinsfile updates.  Then didn't use make for Jenkins.  Didn't want to lose this change.
> add rule to make coverage

- Makefile
Hopefully I've got the dependencies set correctly now.
> Set dependencies for rules
