api.py, conduce.py, config.py, session.py
Added this command:
```
python conduce/conduce.py config set api-key --host=banksy-dev.conduce.com --user=enterprise_test@conduce.com --new
```
User must specify --key or --new.  Otherwise a ValueError will be thrown.
=> Generate and set api key

config.py
If a new user tries to use the utility to generate an API key because the email address does not exist in the configuration.  Busch league.  This change validates the key is valid before checking the value.
=> Ensure user exists before checking api-key

README.md
Remove the references to running the command line utility from source
and provide instructions for installing with pip.
=> Updated readme for module installation

requirements.txt
Used by util.py.  Needed for readthedocs.
=> Added python-dateutil

requirements.txt, setup.py, util.py
Allows the timezone in the string to be replaced by a user specified timezone.  Primarily to be used in cases where the timezone is not specified in the string and the timestamp is known to be in local time.
=> Apply user specified timezone to parsed datetime

api.py
If user passes 'conduce/api' in uri fragment don't prepend
'conduce/api/v1'
=> Accept more literal URIs

api.py, conduce.py, setup.py, util.py
Removed endpoints for orchestration, userasset, substrate, and template.  Use resource API instead.  Datasets, substrates, orchestrations, assets, and lens templates are now created and destroyed with the resource API.
Raw resources are returned in their raw format.  All others are returned as a list or dictionary.  
Convenience methods are provided where the REST API takes a `type` parameter (create, find, remove).
There is no implementation of the PATCH API at this time.
=> v2 Resource API support

README.md, requirements-all.txt, requirements-docs.txt
Splitting runtime requirements from documentation requirements.  ReadTheDocs should be updated to use `requirements-all.txt` after this is merged.
=> split requirements

README.md, api.py, conduce.py, doc/source/api-key-creation.rst, doc/source/conf.py, doc/source/getting-started.rst, doc/source/index.rst
This adds the documentation for creating api keys.  There is some cleanup work to be done in index.rst that is outside the scope of this story.
Please review this document:
https://conduce-conduce-python-api.readthedocs-hosted.com/en/feature-doc-create-api-key/api-key-creation.html 
and make comments here.
There are also code changes made to accommodate the documentation.
Exit criteria:
A non-Conduce expert can read this document and create an API key assuming they have a Conduce account and understand how to install a Python package.
=> doc create api key

doc/source/conduce-entities.rst
Somehow this got overlooked in the add `ingest_samples` API story.
=> Changed `ingest_entities` to `ingest_samples`

api.py
This change converts anything the user passes as an ID field to a string.  Any exceptions are raised to the user to handle.
This makes the code consistent with the example in "Conduce Entities" where integers are used as IDs.
=> Convert ID field to string.

.gitignore, api.py
For object methods, we should be using `:py:meth:` instead of `:py:func:`
http://www.sphinx-doc.org/en/stable/domains.html#role-py:meth
=> fix links to external library methods in documentation

README.md, doc/source/api-key-creation.rst, doc/source/data-ingest.rst
two outstanding issues that I wasn't able to indicate with edits alone: 
1. when I make a conduce-api request without adding an API key manually, I don't get a password prompt as the documentation seems to indicate. Instead I just get an Authorization required error basically. I'm making a ticket for this. 
2. When to use ingest_samples vs ingest_entities is still a bit confusing. 
i. An entity is a list of samples right? so why can't I use api.ingest_samples(dataset_id, entity,...) ? 
ii. What do I do if some of the records I am adding are samples (part of an existing entity already in the dataset) and some are entities (haven't been seen before)? Is this allowed?
iii. What if I don't know whether something is an entity or a sample? There might be more updates to this id coming along but …
=> Alex revisions

conduce.py
This change adds an edit command to `conduce-api` that automatically opens a resource in an editor and updates the resource after the user saves changes and exits the editor.
I've tested this with editing hoverbox configuration.  I'm not sure what happens if there is invalid syntax.  I'm hoping `json` covers that.
=> Added command for editing text based resources

acl.py
This change ensures that email address comparisons are done with lowercase characters.  It should be noted that this is in conflict with the standard:
>The local-part of a mailbox MUST BE treated as case sensitive.  Therefore, SMTP implementations MUST take care to preserve the case   of mailbox local-parts.  In particular, for some hosts, the user "smith" is different from the user "Smith".  However, exploiting the case sensitivity of mailbox local-parts impedes interoperability and is discouraged.  Mailbox domains follow normal DNS rules and are hence not case sensitive.
=> ignore case email check

api.py, conduce.py
This command enables a user to edit a single instance of an entity.  The
user specifies the dataset ID and the entity ID with an optional date
string.  The entity is opened in an editor for modification, after which
the modified entity is updated in the dataset.
=> Added command for editing entities from a dataset

conduce.py, setup.py
Also updated the package description.
This is a basic command for creating resources.  It assumes the user has a fully defined content file.  It does no content validation.
I tested it by creating a lens template with `samples/world-cities-lens.json`.  I was then able to edit the resource to add the dataset ID and make it valid.
=> Added command for creating resources

samples/create_world_cities.py, samples/world-cities-lens.json
Create a dataset, ingest the world cities data, create a lens template that points to the data, and set public permissions to view the data.
This may be useful for populating deploys.  This works with an API key or one-time password authentication.
=> Added example script that creates world cities lens

session.py
This allows for the creation of a new API key when the current key in the conduceconfig is invalid.
We were hitting this issue on deploy boxes.  Once a jenkins slave created an API key for a deploy, the config would be written with that key.  After the box is destroyed and the name reused, the deploy script could no longer generate a new API key because all attempts to do so would use the old (now invalid) API key stored in the config.
These precedence rules should be correct in general because a password provided by a user should be the overriding choice anyway.
We also should add some mechanism to remove an API key from conduceconfig, but that can be handled with future work.
=> When a password is explicitly provided, it should override an existing API key

api.py, setup.py
This changes adds more careful status checks while waiting for ingest jobs to complete.  After this change `wait_for_job` will not return on a 500 error.  It will retry.  The function should still return immediately on a 400 error.
=> SKW-2883: more robust waiting

api.py
This was causing dhl ingest daemons (at least one) to crash.
=> response is not defined here, use e.response

api.py, conduce.py, setup.py
Adds a CLI command to create a tileset.  User provides the mapbox url to the tileset definition.
Necessary to support a documented way to add a tileset.
=> SKW-3284: create tileset

api.py, setup.py
The `compose_uri` method was checking for "api" in the URI fragment and assuming it was a complete URI if the string was present.  Doesn't seem like the greatest check.
This is a quick fix to make the `apikeys/list` URI work again.
=> apikey uris have api in them

conduce.py
Just lets a dev run from source.  Otherwise it errors out because it can't find the conduce module.
=> check to see if being run from source

api.py, conduce.py, setup.py
Adds support for hard delete (permanent=true) via the `--hard` flag.
Also fixes a bug that prevented headers from being printed after a `remove_resource` call.
=> Added support for hard delete

api.py, asset.py, conduce.py, setup.py
Now users can add/remove/set tags via command line arguments.  Users can also search and remove by tag.
Multiple tags may be specified by providing multiple `--tags` arguments.
=> CLI tagging support

setup.py, util.py
Invalid syntax caused type checks to fail in all cases.  It went unnoticed because the exception was caught and the attributes were parsed as strings.
This bug would impact production for any ingest daemon that calls `dict_to_entities`.
=> Don't raise exception on numbers

api.py, conduce.py, doc/Makefile, session.py, setup.py
Self-signed SSL certificates fail verification.  This PR adds a
--noverify command line flag to the conduce api utility to skip SSL
certificate verification.
=> Add --no-verify option to ignore SSL certificate errors

conduce.py
I found one more path through the code where a request was being made that verified SSL certificates.
`python conduce.py config set api-key --new --user=<username> --host=<host> --password <password> --no-verify`
This calls the create a new api key through the api, and then saves it in the config file.  But because of the nested levels of argument parsing, --no-verify wasn't a valid option on a config parser.
=> Add option to new key creation as well

samples/create_world_cities.py
Add --no-verify option to the create_world_cities.py script.  Since args get
passed down directly to the python conduce api calls, this will allow
this script to connect a self-signed SSL certificate.
=> Add --no-verify to create_world_cities script

api.py, conduce.py
Allows a user to ingest a "raw" entity set json file.  This was useful for ingesting a bin-centers file from a script of which the output was an entity set JSON.
=> ingest entitiy set

util.py
I ran into issues ingesting a simple CSV file because the end times were all being set to INFINITY when they should have been set to timestamp_ms.  This change ensures that endtime is set to timestamp unless endtime is specified or the `--infinite` flag is passed.
=> Set endtime to timestamp if not specified

conduce/cli.py
I thought `from builtin import str` was suppose to take care of this, but I guess it doesn't.  I was getting type === str but isinstance(x,str) did not work.  Stackoverflow suggested in the fix implemented here which works for python 2 and 3.
Also result.content was bytes not str in Python 3 so this fix includes decoding the response content.
Also refactored pretty printing into a reusable function.
=> Re-enable CLI pretty printing

conduce/config.py
I needed to test config.py, it turned out to be PEBCAK.  Anyway, now a developer can use this to parse and print information from the config file.
In other news, don't misuse the variable name `HOME` in bash scripts.
=> Make config.py main less completely broken

conduce/cli.py
edit command was failing because it was trying to write a string to a binary file.  This change updates the file mode to text to get the command working again.
=> Write tempfile in text mode

conduce/cli.py, setup.py
When user passes `-s` or `--short` to `conduce-api find` a shortened list will returned with one line per resource.  
Hmm, maybe the option should be `--one-line` and `-1`.
=> add option to display only name: id in find list

conduce/cli.py, setup.py
Resource ID argument is now parsed as a comma separated list (no spaces) and permissions are applied to all resources (one or more) in the list.
=> Enable user to set permissions on list of resources

conduce/cli.py, setup.py
print empty string when no name exists and "None" when no ID exists (impossible).
=> don't crash on unnamed resources

conduce/api.py, conduce/ingest.py, conduce/util.py, doc/source/conduce-entities.rst, doc/source/entity-sample-definitions.rst, setup.py, test/test_util.py
This change moves some utility functions out of api.py.  These functions convert samples (as defined in the documentation) to entity sets.  They are valuable outside the api package.
EDIT:  I also threw in a documentation fix for some syntax error in examples.
=> util cleanup

tools/jenkins/pipeline_master.groovy
Comment out the tag release stage for now.
=> stop tagging commits to master

conduce/api.py, conduce/cli.py, test/test_api.py, test/test_util.py
This change adds post transaction methods to the Python API.
Updates documentation and tests.
Fixes bad code in json_to_samples.
Not changing the version number until all API methods have been updated. (Let me know if that's a bad idea.)
=> SKW-4167: post transaction methods and cli

conduce/api.py, conduce/cli.py, test/test_api.py
This adds the GET endpoint and a passthrough CLI, the only difference being the API default to returning only the last transaction instead of all transactions.
=> SKW-4167: get transaction methods and cli

conduce/api.py, test/test_api.py
Adds API for delete_transactions.  Does not change the CLI.  CLI will be updated when high level `clear_dataset` is modified to call `delete_transactions`.
=> SKW-4167: delete transactions

Makefile, conduce/api.py, test/test_api.py
Adds generic method to create a backend, only valid backend types are accepted.
Adds convenience methods for all valid backend types.
No CLI support in this PR.
=> SKW-4168: create dataset backends

conduce/api.py, test/test_api.py
Add method to get backends (1 method) and methods (3) to patch backends (process transactions and set auto_process flag).
No CLI support in this PR.  Builds on create backend methods.
EDIT: Also contains methods for get backend metadata, delete backend, and search backend.
=> SKW-4168: other backends methods

Makefile
This change uses the PYENV_VERSION environment variable instead of the `pyenv local` command to set the python version when creating virtual environments.  Once the virtual environments are created pyenv has done its job and is no longer required.
=> Do pyenv the right way

conduce/api.py, conduce/cli.py, test/test_api.py, test/test_cli.py
Updates create dataset to process an additional kwarg backend_types (list).  When backend types are defined and valid the default backend is removed and backends of the type in the array are added.
Also updates CLI for `dataset create` and `create-dataset`.
=> SKW-4169: update create dataset

conduce/cli.py, test/test_cli.py
min defaults to -1 in the CLI.  This change causes value to override min/max rather than print an error.
An alternative would be to only remove min if -1 and value specified.
=> Remove min/max if value specified

conduce/cli.py, test/test_cli.py
kwargs were not passed to wait_for_transaction causing all requests to
go to users default.  max_transaction was set to count, now count - 1.
=> Fix cli.process_transactions

conduce/api.py
kwargs.get uses the second parameter as the default if the property is
not found on an object.  But in this case, cli.py is passing
timeout=None, so the default is not used.  instead, kwargs.get returns
None.  This results in an exception when trying to multiply None * 2.
This change drops the default parameter and does an explicit test for
timeout is None, setting to our chosen default if necessary.  Then
performs the multiply by 2 when we're sure we have a number.
=> Check for timeout is None

conduce/api.py, test/test_api.py
There is a method dedicated to setting the default backend.  It is confusing to include it here.
=> Remove default from process transactions

conduce/api.py, test/test_api.py
I kept getting tripped up by this line of code, thinking it was checking for `not process`.  This cleanup also removes the superfluous kwargs from subsequent calls, which led to test cleanup.
This should result in clearer code and tests.
=> Updated for clarity
